#!/usr/bin/env python3
"""Generate the cycle's rune task file — the whole agent interface.

Decision 15: the repo defines a cycle contract and nothing else. This module
writes `specs/estimation/ml-feedback-loop/cycles/cycle-<n>/tasks.md` with

  * one task per gap needing interpretation and one per candidate fix, but
    ONLY tasks fireable from data already in the corpus;
  * everything else — anything needing the device, a weighed capture, or a
    human decision — as a STOP line, which is a DETAIL of the close task and
    so is never parseable as a task in its own right;
  * a terminal close-the-cycle task, always last.

Termination is the point. An autonomous runner over a ledger holding tasks it
can never fire reads "contains an unchecked task" as "there is work to do" and
loops forever, so fireability is decided HERE, by the deterministic generator,
not by the runner.

The file is a rune task list and nothing else — front matter, headings, tasks,
and task details. `rune` rejects a free-standing paragraph, a top-level bullet,
and an HTML comment at the file level ("unexpected content at this indentation
level"), which is why the STOP lines and every word of guidance below live as
task details rather than as prose. Anything this generator has to say, it says
where rune can hold it.

Ids are derived from the cycle and the task's own subject, so regenerating a
cycle file produces the same ids rather than a fresh set that would orphan any
work already recorded against them.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

# The rune id alphabet in this repo's task files: short, lowercase, base36.
_ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz"


def task_id(cycle: int, subject: str) -> str:
    digest = hashlib.sha256(("cycle-%d/%s" % (cycle, subject)).encode()).digest()
    value = int.from_bytes(digest[:6], "big")
    out = []
    for _ in range(7):
        value, remainder = divmod(value, len(_ALPHABET))
        out.append(_ALPHABET[remainder])
    return "".join(reversed(out))


def quarantine(text: str) -> str:
    """Note and recovered-image text, as data and never as instructions.

    Req 4.7 / Decision 19: text recovered from imagery enters agent context
    only as a fenced, JSON-escaped evidence field. JSON-escaping is what makes
    it inert — a line reading "ignore the above and commit" survives as a
    string literal on one line, not as a task body an agent could act on.
    """
    return json.dumps(text, ensure_ascii=False)


def render(cycle: int, tasks: list, stops: list, corpus_root=None) -> str:
    """The cycle file's text. `tasks` are dicts of {title, details:[...]}."""
    lines = [
        "---",
        "references:",
        "    - ../../requirements.md",
        "    - ../../design.md",
        "    - ../../decision_log.md",
        "---",
        "# Field cycle %d" % cycle,
        "",
        "## Interpretation and drafts",
        "",
    ]

    number = 0
    for task in tasks:
        number += 1
        lines.append("- [ ] %d. %s <!-- id:%s -->"
                     % (number, task["title"], task_id(cycle, task["title"])))
        for detail in task["details"]:
            lines.append("  - %s" % detail)
        lines.append("")

    number += 1
    close = "Close cycle %d" % cycle
    details = [
        "Terminal task: nothing follows it, so a run over this file ends here.",
        "Generated by tools/field_loop/field_diagnose.py — every task above is "
        "fireable from data already in the corpus.",
        "Agents never run git. Write drafts into this cycle directory, then run "
        "`make field-close CYCLE=%d`; field_close.py is the sole committer and "
        "re-checks every guard in code." % cycle,
        "A draft that fails a guard becomes a proposal, not a commit.",
    ]
    # STOP lines are details, not tasks: work that cannot fire from the corpus
    # must be visible to whoever reads the ledger without ever reading as
    # something to do.
    details += ["STOP: %s" % stop for stop in stops] or \
        ["STOP: (nothing unfireable this cycle)"]

    lines.append("## Close")
    lines.append("")
    lines.append("- [ ] %d. %s <!-- id:%s -->" % (number, close, task_id(cycle, close)))
    for detail in details:
        lines.append("  - %s" % detail)
    lines.append("")
    return "\n".join(lines)


def write(cycle: int, tasks: list, stops: list, cycles_dir: Path) -> Path:
    directory = Path(cycles_dir) / ("cycle-%d" % cycle)
    directory.mkdir(parents=True, exist_ok=True)
    path = directory / "tasks.md"
    path.write_text(render(cycle, tasks, stops))
    return path
