"""Liquid DB rows, provenance columns, and new tables (nutrition5k-calibration).

Req 7.1: 8 coarse liquid classes (water, coffee, tea, milk, fruit_juice, soup,
beer, wine) appended to FOOD_DATA, each with a carb value, density, and per-row
source. Req 5.4: ``beta_provenance`` (TEXT NOT NULL DEFAULT 'none') and
``device_verified`` (INTEGER NOT NULL DEFAULT 0) columns on ``foods``.
Req 7.4/7.7: ``liquid_servings`` holds region-keyed canonical serving volumes
under a CLOSED region/vessel vocabulary — an out-of-vocabulary value is a hard
error at insert, and lookups miss loudly rather than returning zero.
Req 7.5 / Decision 24: ``liquid_subclasses`` carries best-effort sub-class
densities (beer -> lager/stout); sub-classes are DB rows, never palette channels.

These tests bake into a temp dir (they exercise generate.py itself, not the
committed artifact — the committed DBs are regenerated by the palette-lock task).
"""

import sqlite3

import pytest

import generate

LIQUID_CLASSES = ["water", "coffee", "tea", "milk",
                  "fruit_juice", "soup", "beer", "wine"]
SOLID_COUNT = 24


@pytest.fixture(scope="module")
def baked(tmp_path_factory):
    """Bake both DBs into a temp dir; restore module paths afterwards."""
    out = tmp_path_factory.mktemp("food_db_bake")
    saved = (generate.OUTPUT_DIR, generate.COFID_DB, generate.AFCD_DB)
    generate.OUTPUT_DIR = str(out)
    generate.COFID_DB = str(out / "cofid_db.sqlite")
    generate.AFCD_DB = str(out / "afcd_db.sqlite")
    try:
        generate.bake()
        yield {"cofid": generate.COFID_DB, "afcd": generate.AFCD_DB}
    finally:
        generate.OUTPUT_DIR, generate.COFID_DB, generate.AFCD_DB = saved


def connect(path):
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn


# --- FOOD_DATA content (Req 7.1) ---

def test_food_data_is_24_solid_plus_8_liquid():
    ids = [row[0] for row in generate.FOOD_DATA]
    assert len(ids) == SOLID_COUNT + len(LIQUID_CLASSES), (
        f"FOOD_DATA must hold 24 solid + 8 liquid classes, got {len(ids)}"
    )
    # Channel order is load-bearing: liquids append after the solids in
    # ClassPalette.v1Standard declaration order (Decision 23/24).
    assert ids[SOLID_COUNT:] == LIQUID_CLASSES
    assert ids[0] == "white_rice"
    assert ids[SOLID_COUNT - 1] == "mixed_vegetables"


def test_liquid_rows_carry_carb_density_and_source():
    rows = {row[0]: row for row in generate.FOOD_DATA}
    for class_id in LIQUID_CLASSES:
        row = rows[class_id]
        density, carbs = row[2], row[4]
        density_source, composition_source = row[10], row[11]
        assert 0.9 <= density <= 1.1, (
            f"{class_id} density {density} not a plausible liquid g/cm³"
        )
        assert carbs >= 0.0
        assert density_source, f"{class_id} missing per-row density source"
        assert composition_source, f"{class_id} missing per-row composition source"


# --- foods schema: provenance + device_verified (Req 5.4) ---

def foods_columns(conn):
    return {r["name"]: r for r in conn.execute("PRAGMA table_info(foods)")}


@pytest.mark.parametrize("db_key", ["cofid", "afcd"])
def test_foods_schema_has_provenance_and_device_verified(baked, db_key):
    conn = connect(baked[db_key])
    try:
        cols = foods_columns(conn)
        assert "beta_provenance" in cols
        assert cols["beta_provenance"]["notnull"] == 1
        assert cols["beta_provenance"]["dflt_value"] == "'none'"
        assert "device_verified" in cols
        assert cols["device_verified"]["notnull"] == 1
        assert cols["device_verified"]["dflt_value"] == "0"
    finally:
        conn.close()


def test_uncalibrated_bake_defaults_provenance_none_and_unverified(baked):
    conn = connect(baked["cofid"])
    try:
        rows = conn.execute(
            "SELECT class_id, beta_provenance, device_verified FROM foods"
        ).fetchall()
        assert rows, "baked foods table is empty"
        for row in rows:
            assert row["beta_provenance"] == "none", row["class_id"]
            assert row["device_verified"] == 0, row["class_id"]
    finally:
        conn.close()


def test_baked_cofid_contains_liquid_rows(baked):
    conn = connect(baked["cofid"])
    try:
        ids = {r["class_id"] for r in conn.execute("SELECT class_id FROM foods")}
        assert set(LIQUID_CLASSES) <= ids
    finally:
        conn.close()


# --- liquid_servings (Req 7.4/7.7) ---

def test_liquid_servings_rows_are_region_keyed_with_provenance(baked):
    conn = connect(baked["cofid"])
    try:
        rows = conn.execute(
            "SELECT class_id, region, vessel, serving_ml, source "
            "FROM liquid_servings"
        ).fetchall()
        assert rows, "liquid_servings must ship canonical serving volumes"
        for row in rows:
            assert row["class_id"] in LIQUID_CLASSES
            assert row["serving_ml"] > 0
            assert row["source"], (
                f"{row['class_id']}/{row['region']}/{row['vessel']} "
                "missing provenance"
            )
        # The canonical example from Req 7.7: the UK pint is 568 mL.
        uk_pint = conn.execute(
            "SELECT serving_ml FROM liquid_servings "
            "WHERE class_id = 'beer' AND region = 'UK' AND vessel = 'pint'"
        ).fetchone()
        assert uk_pint is not None
        assert uk_pint["serving_ml"] == pytest.approx(568.0)
    finally:
        conn.close()


def test_liquid_servings_primary_key_is_class_region_vessel(baked):
    conn = connect(baked["cofid"])
    try:
        pk = [r["name"] for r in
              sorted(conn.execute("PRAGMA table_info(liquid_servings)"),
                     key=lambda r: r["pk"]) if r["pk"] > 0]
        assert pk == ["class_id", "region", "vessel"]
    finally:
        conn.close()


def test_liquid_servings_vocabulary_is_closed(baked):
    # Out-of-vocabulary region/vessel must be a hard error at the DB layer —
    # not a row a lookup would silently miss (Req 7.4/7.7).
    conn = connect(baked["cofid"])
    try:
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO liquid_servings VALUES "
                "('beer', 'Narnia', 'pint', 568.0, 'test')"
            )
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO liquid_servings VALUES "
                "('beer', 'UK', 'bucket', 5000.0, 'test')"
            )
    finally:
        conn.close()


# --- liquid_subclasses (Req 7.5, Decision 24) ---

def test_liquid_subclasses_has_beer_lager_and_stout(baked):
    conn = connect(baked["cofid"])
    try:
        rows = {r["sub_class"]: r for r in conn.execute(
            "SELECT sub_class, carbs_mono_100, density, source "
            "FROM liquid_subclasses WHERE class_id = 'beer'"
        )}
        assert {"lager", "stout"} <= set(rows)
        for sub, row in rows.items():
            assert row["carbs_mono_100"] >= 0.0, sub
            assert 0.9 <= row["density"] <= 1.1, sub
            assert row["source"], f"beer/{sub} missing provenance"
    finally:
        conn.close()


def test_liquid_subclasses_primary_key_is_class_and_subclass(baked):
    conn = connect(baked["cofid"])
    try:
        with pytest.raises(sqlite3.IntegrityError):
            conn.execute(
                "INSERT INTO liquid_subclasses "
                "SELECT * FROM liquid_subclasses "
                "WHERE class_id = 'beer' AND sub_class = 'lager'"
            )
    finally:
        conn.close()
