"""solid_servings table tests (serving-adjust PRD, Food database servings Req 1).

The generator emits ``solid_servings`` alongside the ``liquid_servings``
precedent: one household serving definition per solid palette class —
``(class_id, unit_singular, unit_plural, grams_per_unit, step, source)``.
``step`` is the stepper increment in serving units so granularity is data,
not code.

Coverage rule: every non-liquid class in ``foods`` either has a row or is
listed as deliberately absent (``SOLID_SERVINGS_ABSENT``); a class id in
``solid_servings`` that does not exist among the solid classes (an orphan or
a liquid) fails generation before anything is written.

Provenance rule: BDA-sourced rows cite the BDA Food Fact Sheet URL; the
figures the research pass could not verify against a free authoritative
source carry the honest string "Crawley Food Portion Sizes (unverified
figure)".

These tests bake into a temp dir (they exercise generate.py itself, not the
committed artifact — the committed DBs are regenerated by the same change).
"""

import sqlite3

import pytest

import generate

SOLID_COUNT = 25

BDA_URL = "bda.uk.com/resource/food-facts-portion-sizes"
CRAWLEY_SOURCE = "Crawley Food Portion Sizes (unverified figure)"
# cereal: BDA quotes dry oats only; the as-served spoon figure is unverified
# (myfoodrepo-bridge PRD, palette v2).
CRAWLEY_CLASSES = {"potato_mashed", "lentils", "chips_fries", "salad_leaves",
                   "cereal"}

# Seed gram weights per PRD Req 1's acceptance list.
EXPECTED_GRAMS = {
    "bread_white": 36.0, "bread_wholemeal": 36.0,
    "potato_boiled": 58.0, "potato_mashed": 60.0,
    "white_rice": 50.0, "brown_rice": 50.0, "pasta": 50.0,
    "peas": 27.0, "mixed_vegetables": 27.0, "broccoli": 27.0, "carrot": 27.0,
    "beans_baked": 37.0, "lentils": 37.0,
    "chips_fries": 55.0,
    "apple": 80.0, "banana": 80.0, "tomato": 80.0,
    "cheese": 30.0, "egg": 50.0,
    "beef": 90.0, "chicken": 90.0, "pork": 90.0, "fish_white": 90.0,
    "salad_leaves": 20.0,
    # Palette v2 addition (myfoodrepo-bridge PRD): as-served porridge spoon.
    "cereal": 50.0,
}


def solid_class_ids():
    return [row[0] for row in generate.FOOD_DATA[:SOLID_COUNT]]


def liquid_class_ids():
    return [row[0] for row in generate.FOOD_DATA[SOLID_COUNT:]]


@pytest.fixture(scope="module")
def baked(tmp_path_factory):
    """Bake both DBs into a temp dir; restore module paths afterwards."""
    out = tmp_path_factory.mktemp("food_db_solid_bake")
    saved = (generate.OUTPUT_DIR, generate.COFID_DB, generate.AFCD_DB)
    generate.OUTPUT_DIR = str(out)
    generate.COFID_DB = str(out / "cofid_db.sqlite")
    generate.AFCD_DB = str(out / "afcd_db.sqlite")
    try:
        generate.bake()
        yield {"cofid": generate.COFID_DB, "afcd": generate.AFCD_DB}
    finally:
        generate.OUTPUT_DIR, generate.COFID_DB, generate.AFCD_DB = saved


def connect(path):
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    return conn


# --- schema ---

def test_solid_servings_schema_and_primary_key(baked):
    conn = connect(baked["cofid"])
    try:
        cols = list(conn.execute("PRAGMA table_info(solid_servings)"))
        assert [c["name"] for c in cols] == [
            "class_id", "unit_singular", "unit_plural",
            "grams_per_unit", "step", "source",
        ]
        pk = [c["name"] for c in cols if c["pk"] > 0]
        assert pk == ["class_id"]
    finally:
        conn.close()


def test_solid_servings_lives_in_cofid_only(baked):
    # Mirror of liquid_servings: a lookup table, not composition data — one
    # home avoids merge semantics; AFCD carries the empty shared-schema table.
    conn = connect(baked["afcd"])
    try:
        rows = conn.execute("SELECT * FROM solid_servings").fetchall()
        assert rows == []
    finally:
        conn.close()


# --- coverage rule ---

def test_every_solid_class_has_row_or_is_deliberately_absent(baked):
    conn = connect(baked["cofid"])
    try:
        served = {r["class_id"]
                  for r in conn.execute("SELECT class_id FROM solid_servings")}
    finally:
        conn.close()
    solids = set(solid_class_ids())
    absent = set(generate.SOLID_SERVINGS_ABSENT)
    assert served | absent == solids, (
        "every solid class must have a solid_servings row or be listed "
        "deliberately absent"
    )
    assert served & absent == set(), (
        "a class cannot both have a row and be deliberately absent"
    )


def test_no_liquid_class_in_solid_servings(baked):
    conn = connect(baked["cofid"])
    try:
        served = {r["class_id"]
                  for r in conn.execute("SELECT class_id FROM solid_servings")}
    finally:
        conn.close()
    assert served & set(liquid_class_ids()) == set()


# --- generation failures (orphan / liquid / silent coverage gap) ---

def bake_to(tmp_path, monkeypatch):
    monkeypatch.setattr(generate, "OUTPUT_DIR", str(tmp_path))
    monkeypatch.setattr(generate, "COFID_DB", str(tmp_path / "cofid_db.sqlite"))
    monkeypatch.setattr(generate, "AFCD_DB", str(tmp_path / "afcd_db.sqlite"))
    generate.bake()


def test_orphan_class_id_fails_generation(tmp_path, monkeypatch):
    monkeypatch.setattr(
        generate, "SOLID_SERVINGS",
        generate.SOLID_SERVINGS
        + [("dragonfruit", "piece", "pieces", 80.0, 1.0, "test")])
    with pytest.raises(SystemExit, match="dragonfruit"):
        bake_to(tmp_path, monkeypatch)
    assert not (tmp_path / "cofid_db.sqlite").exists(), (
        "a failing bake must leave no output"
    )


def test_liquid_class_id_fails_generation(tmp_path, monkeypatch):
    monkeypatch.setattr(
        generate, "SOLID_SERVINGS",
        generate.SOLID_SERVINGS
        + [("water", "glass", "glasses", 250.0, 1.0, "test")])
    with pytest.raises(SystemExit, match="water"):
        bake_to(tmp_path, monkeypatch)


def test_grams_per_unit_of_100_or_more_fails_generation(tmp_path, monkeypatch):
    # Precision coupling: ServingNote trims serving counts to 2 dp and the
    # result screen treats parse-derived grams within 0.5 g (gramEpsilon) of
    # the pending amount as unchanged — that round-trip only holds while
    # every grams_per_unit stays below 100 g.
    inflated = [row if row[0] != "potato_boiled"
                else row[:3] + (100.0,) + row[4:]
                for row in generate.SOLID_SERVINGS]
    monkeypatch.setattr(generate, "SOLID_SERVINGS", inflated)
    with pytest.raises(SystemExit, match="potato_boiled"):
        bake_to(tmp_path, monkeypatch)


def test_unlisted_coverage_gap_fails_generation(tmp_path, monkeypatch):
    # Dropping a class's row WITHOUT listing it deliberately absent must fail —
    # absence has to be a decision, never an accident.
    trimmed = [row for row in generate.SOLID_SERVINGS
               if row[0] != "potato_boiled"]
    assert "potato_boiled" not in generate.SOLID_SERVINGS_ABSENT
    monkeypatch.setattr(generate, "SOLID_SERVINGS", trimmed)
    with pytest.raises(SystemExit, match="potato_boiled"):
        bake_to(tmp_path, monkeypatch)


# --- seed content (PRD Req 1 acceptance list) ---

def test_seed_gram_weights_match_prd(baked):
    conn = connect(baked["cofid"])
    try:
        rows = {r["class_id"]: r for r in conn.execute(
            "SELECT class_id, grams_per_unit FROM solid_servings")}
    finally:
        conn.close()
    assert set(rows) == set(EXPECTED_GRAMS)
    for class_id, grams in EXPECTED_GRAMS.items():
        assert rows[class_id]["grams_per_unit"] == pytest.approx(grams), class_id


def test_rows_have_units_positive_grams_and_step(baked):
    conn = connect(baked["cofid"])
    try:
        rows = conn.execute("SELECT * FROM solid_servings").fetchall()
    finally:
        conn.close()
    assert rows
    for row in rows:
        assert row["unit_singular"], row["class_id"]
        assert row["unit_plural"], row["class_id"]
        assert row["grams_per_unit"] > 0, row["class_id"]
        assert row["step"] > 0, row["class_id"]


def test_provenance_is_honest_per_row(baked):
    # BDA rows cite the Food Fact Sheet URL; the four figures the research
    # pass could not verify carry the exact unverified-Crawley string.
    conn = connect(baked["cofid"])
    try:
        rows = conn.execute(
            "SELECT class_id, source FROM solid_servings").fetchall()
    finally:
        conn.close()
    for row in rows:
        if row["class_id"] in CRAWLEY_CLASSES:
            assert row["source"] == CRAWLEY_SOURCE, row["class_id"]
        else:
            assert BDA_URL in row["source"], row["class_id"]
